name: Deploy Laravel Application to Github Actions
on: [push]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest

        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: media_team_app
        ports:
          - 8888:3306

        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 -h 127.0.0.1

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Install PHP packages
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Start the MySql Service
        run: sudo systemctl start mysql

      - name: Create the DB
        run: sudo mysql -h 127.0.0.1 --port 8888 -u root -proot -e 'CREATE DATABASE IF NOT EXISTS media_team_app;'

      - name: Seed Data in the Database
        run: php artisan migrate --seed

      - name: Run Application
        run: php artisan serve
        # GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'password';
